repo_id: kyutai/moshika-vis-pytorch-bf16
mimi_name: tokenizer-e351c8d8-checkpoint125.safetensors
duration_sec: 10.0

data:
  train_data: /workspace/data/speech/train_data_refined_a.jsonl
  eval_data: /workspace/j-moshivis/dataset/eval
  image_root: /mnt/sub_storage/images/
  shuffle: true
  speech_ratio: 0.25

train:
  batch_size: 8
  seed: 42
  num_workers: 0

trainer:
  batch_size: 8
  text_padding_weight: 0.0
  first_codebook_weight_multiplier: 3.0
