repo_id: kyutai/moshika-vis-pytorch-bf16
mimi_name: tokenizer-e351c8d8-checkpoint125.safetensors
duration_sec: 10.0

data:
  train_data: /workspace/data/speech/train_data.jsonl
  eval_data: /workspace/j-moshivis/dataset/eval
  image_root: /mnt/sub_storage/images/
  shuffle: true

train:
  batch_size: 1
  seed: 42
  num_workers: 4

trainer:
  text_padding_weight: 0.1
  first_codebook_weight_multiplier: 3.0
